# Cursor size
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Don't show update on first launch
ecosystem {
  no_update_news = true
}

# Use XCompose file
env = XCOMPOSEFILE,~/.XCompose

# XDG Desktop Portal
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# QT
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1

# Disable appimage launcher by default
env = APPIMAGELAUNCHER_DISABLE,1

# Force all apps to use Wayland
env = GDK_BACKEND,wayland,x11,*
env = CLUTTER_BACKEND,wayland
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_STYLE_OVERRIDE,kvantum
env = SDL_VIDEODRIVER,wayland
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = OZONE_PLATFORM,wayland

xwayland {
    force_zero_scaling = true
}
